Update setup.py
Traceback (most recent call last):
  File "setup.py", line 41, in <module>
    for ir in parse_requirements('requirements.txt')]
  File "/home/nilc/.local/lib/python2.7/site-packages/pip/req/req_file.py", line 79, in parse_requirements
    "parse_requirements() missing 1 required keyword argument: "
TypeError: parse_requirements() missing 1 required keyword argument: 'session'